//============================================================================
// PROJECT  :  F1L StarterKit
//============================================================================
//                           C O P Y R I G H T
//============================================================================
// Copyright (c) 2013 by Renesas Electronics  GmbH. All rights reserved.
// Arcadiastr.10
// D-40472 Duesseldorf
// Germany
//============================================================================
//
// Warranty Disclaimer :
// Because the Product(s) is licensed free of charge, there is no warranty of
// any kind whatsoever and expressly disclaimed and excluded by Renesas, either
// expressed or implied, including but not limited to those for non-
// infringement of intellectual property, merchantability and/or fitness for
// the particular purpose. Renesas shall not have any obligation to maintain,
// service or provide bug fixes for the supplied Product(s) and/or the
// Application.
//
// Each User is solely responsible for determining the appropriateness of
// using the Product(s) and assumes all risks associated with its exercise
// of rights under this Agreement, including, but not limited to the risks
// and costs of program errors, compliance with applicable laws, damage to
// or loss of data, programs or equipment, and unavailability or
// interruption of operations.
//
// Limitation of Liability :
// In no event shall Renesas be liable to the User for any incidental,
// consequential, indirect, or punitive damage (including but not limited to
// lost profits) regardless of whether such liability is based on breach of
// contract, tort, strict liability, breach of warranties, failure of
// essential purpose or otherwise and even if advised of the possibility of
// such damages. Renesas shall not be liable for any services or products provided
// by third party vendors, developers or consultants identified or referred
// to the User by Renesas in connection with the Product(s) and/or the
// Application.
//
//============================================================================
//
// CAN Rx rule table
//
//============================================================================

//============================================================================
// Includes
//============================================================================
#include "can_table.h"

//============================================================================
// Functions
//============================================================================

/******************************************************************************
** Function:    RX_RULE_TABLE_LIST
** Description: This is the Rx Rule table, automatically generated by Renesas 
**              CAN Configurator 
** Parameter:   RX_RULE_NUM
** Return:      None
******************************************************************************/
/* Rx Rule Table */
/*
Receive Rule ID Register: For the standard ID, set the ID in bits b10 to b0, ext ID: b28 to b0

Receive Rule Mask Register: set to 1--The corresponding bit is compared

Receive Rule Pointer 0 Register: 31to28 Receive Rule DLC check, receive buffer assignment

Receive Rule Pointer 1 Register: FIFO buffer assignment
*/

const can_cre_type RX_RULE_TABLE_LIST[RX_RULE_NUM] = {
/* CAN 0 reception rules */
    {0x00000010UL, 0xDFFFFFF0UL, 0x00008000UL, 0x00000000UL}, /* NO.000 : std data frm ID = H'10~1F will be accepted, destination Rx Buffer0 */
    {0x00000020UL, 0xDFFFFFF0UL, 0x00008100UL, 0x00000000UL}, /* NO.001 : std data frm ID = H'20~2F will be accepted, destination Rx Buffer1 */
    {0x00000030UL, 0xDFFFFFF0UL, 0x00008200UL, 0x00000000UL}, /* NO.002 : std data frm ID = H'30~3F will be accepted, destination Rx Buffer2 */
    {0x00000040UL, 0xDFFFFFF0UL, 0x00008300UL, 0x00000000UL}, /* NO.003 : std data frm ID = H'40~4F will be accepted, destination Rx Buffer3 */
    {0x00000050UL, 0xDFFFFFFFUL, 0x00008400UL, 0x00000000UL}, /* NO.004 : std data frm ID = H'50 will be accepted, destination Rx Buffer4 */
    {0x00000060UL, 0xDFFFFFFFUL, 0x00008500UL, 0x00000000UL}, /* NO.005 : std data frm ID = H'60 will be accepted, destination Rx Buffer5 */
    {0x00000070UL, 0xDFFFFFFFUL, 0x00008600UL, 0x00000000UL}, /* NO.006 : std data frm ID = H'70 will be accepted, destination Rx Buffer6 */
    //{0x00000080UL, 0xDFFFFFF0UL, 0x00008700UL, 0x00000000UL}, /* NO.007 : std data frm ID = H'80~8F will be accepted, destination Rx Buffer7 */   
    {0x00000080UL, 0xDFFFFFF0UL, 0x00000000UL, 0x00000001UL}, /* NO.007 : std data frm ID = H'80~8F will be accepted, destination RX FIFO buffer0 */
    
    {0x90000010UL, 0xDFFFFFF0UL, 0x00008800UL, 0x00000000UL}, /* NO.008 : Ext data frm ID = H'10000010-1F will be accepted, destination Rx Buffer8 */
    {0x90000020UL, 0xDFFFFFF0UL, 0x00008900UL, 0x00000000UL},
    {0x90000030UL, 0xDFFFFFF0UL, 0x00008a00UL, 0x00000000UL},
    {0x90000040UL, 0xDFFFFFF0UL, 0x00008b00UL, 0x00000000UL},
    
    {0x40000010UL, 0xDFFFFFF0UL, 0x00008c00UL, 0x00000000UL}, //std remote ID = H'010-1F
    {0x40000020UL, 0xDFFFFFF0UL, 0x00008d00UL, 0x00000000UL}, //std remote ID = H'020-2F 
    {0xc0000030UL, 0xDFFFFFFFUL, 0x00008e00UL, 0x00000000UL}, //ext remote ID = H'00000030
    {0xc0000040UL, 0xDFFFFFFFUL, 0x00008f00UL, 0x00000000UL}, 
	
/* CAN 1 reception rules */
    {0x00000010UL, 0xDFFFFFF0UL, 0x00009000UL, 0x00000000UL}, /* NO.000 : std data frm ID = H'10~1F will be accepted, destination Rx Buffer H10 */
    {0x00000020UL, 0xDFFFFFF0UL, 0x00009100UL, 0x00000000UL}, /* NO.001 : std data frm ID = H'20~2F will be accepted, destination Rx Buffer H11 */
    {0x00000030UL, 0xDFFFFFF0UL, 0x00009200UL, 0x00000000UL}, /* NO.002 : std data frm ID = H'30~3F will be accepted, destination Rx Buffer H12 */
    {0x00000040UL, 0xDFFFFFF0UL, 0x00009300UL, 0x00000000UL}, /* NO.003 : std data frm ID = H'40~4F will be accepted, destination Rx Buffer H13 */
    {0x00000050UL, 0xDFFFFFFFUL, 0x00009400UL, 0x00000000UL}, /* NO.004 : std data frm ID = H'50 will be accepted, destination Rx Buffer H14 */
    {0x00000060UL, 0xDFFFFFFFUL, 0x00009500UL, 0x00000000UL}, /* NO.005 : std data frm ID = H'60 will be accepted, destination Rx Buffer H15 */
    {0x00000070UL, 0xDFFFFFFFUL, 0x00009600UL, 0x00000000UL}, /* NO.006 : std data frm ID = H'70 will be accepted, destination Rx Buffer H16 */
    {0x00000080UL, 0xDFFFFFF0UL, 0x00000000UL, 0x00000002UL}, /* NO.007 : std data frm ID = H'80~8F will be accepted, destination RX FIFO buffer1 */
		//{0x00000080UL, 0xDFFFFFFFUL, 0x00009700UL, 0x00000000UL}, /* NO.007 : std data frm ID = H'80 will be accepted, destination Rx Buffer H17 */
/* CAN 2 reception rules */
    {0x00000010UL, 0xDFFFFFF0UL, 0x00009000UL, 0x00000000UL}, /* NO.000 : std data frm ID = H'10~1F will be accepted, destination Rx Buffer H10 */
    {0x00000020UL, 0xDFFFFFF0UL, 0x00009100UL, 0x00000000UL}, /* NO.001 : std data frm ID = H'20~2F will be accepted, destination Rx Buffer H11 */
    {0x00000030UL, 0xDFFFFFF0UL, 0x00009200UL, 0x00000000UL}, /* NO.002 : std data frm ID = H'30~3F will be accepted, destination Rx Buffer H12 */
    {0x00000040UL, 0xDFFFFFF0UL, 0x00009300UL, 0x00000000UL}, /* NO.003 : std data frm ID = H'40~4F will be accepted, destination Rx Buffer H13 */
    {0x00000050UL, 0xDFFFFFFFUL, 0x00009400UL, 0x00000000UL}, /* NO.004 : std data frm ID = H'50 will be accepted, destination Rx Buffer H14 */
    {0x00000060UL, 0xDFFFFFFFUL, 0x00009500UL, 0x00000000UL}, /* NO.005 : std data frm ID = H'60 will be accepted, destination Rx Buffer H15 */
    {0x00000070UL, 0xDFFFFFFFUL, 0x00009600UL, 0x00000000UL}, /* NO.006 : std data frm ID = H'70 will be accepted, destination Rx Buffer H16 */
    {0x00000080UL, 0xDFFFFFF0UL, 0x00000000UL, 0x00000004UL}, /* NO.007 : std data frm ID = H'80~8F will be accepted, destination RX FIFO buffer2 */
		//{0x00000080UL, 0xDFFFFFFFUL, 0x00009700UL, 0x00000000UL}, /* NO.007 : std data frm ID = H'80 will be accepted, destination Rx Buffer H17 */

};


